[mysqld]
# Đường dẫn đến thư mục cài đặt MySQL
basedir=D:/mysql

# Đường dẫn đến thư mục chứa dữ liệu (Sẽ tự sinh ra sau)
datadir=D:/mysql/data

# Cổng chạy MySQL mặc định
port=3306

# Cơ chế mã hóa mật khẩu
authentication_policy=caching_sha2_password